image: golang:1.22.2

stages:
  - deps
  - env
  - test
  - build
  - package
  - docker-build

variables:
  BINARY_NAME: "main"
  ZIP_NAME: "main.zip"

before_script:
  - if [[ "$CI_RUNNER_EXECUTABLE_ARCH" == "linux/amd64" ]]; then
      apt-get update && apt-get install -y zip;
      elif [[ "$CI_RUNNER_EXECUTABLE_ARCH" == "linux/arm64" ]]; then
      apt-get update && apt-get install -y zip;
      elif [[ "$CI_RUNNER_EXECUTABLE_ARCH" == "darwin/amd64" ]]; then
      brew install zip;
      elif [[ "$CI_RUNNER_EXECUTABLE_ARCH" == "darwin/arm64" ]]; then
      brew install zip;
      fi


deps:
  stage: deps
  script:
    - make deps

env:
  stage: env
  script:
    - make env

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build

package:
  stage: package
  script:
    - make package

docker-build:
  stage: docker-build
  script:
    - make docker-build
  only:
    - docker