service: serverless-rest-api
frameworkVersion: '>=1.28'
provider:
  name: aws
  runtime: provided.al2023
  region: us-east-1
functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /
          method: GET
package:
  patterns:
    - '!/**' #排除
    - bin/main